name: "Append Version to Image"
description: "Concatenates the version and other image details into on string used for pulling the image"
inputs:
  version:
    description: "The version for the tag"
    type: string
    required: true
    default: "latest"
  registry:
    description: "The registry where the image repository is."
    type: string
    required: true
    default: "FOO_image_registry.com"
  repository:
    description: "The repository name for the image."
    type: string
    required: true
    default: "BAR_image_repo"
outputs:
  tagged_image:
    value: $${{ steps.set_the_output.outputs.tagged_image }}
runs:
  using: "composite"
  steps:
    - name: Echo the input
      id: echo_the_input
      run: |
        echo "Input Version: ${{ inputs.version }}"
        echo "Input Registry: ${{ inputs.registry }}"
        echo "Input Repository: ${{ inputs.repository }}"
      shell: bash
    - name: Set the output
      id: set_the_output
      run: |
        CONCATENATED_VERSION=${{ inputs.registry }}/${{ inputs.repository }}:${{ inputs.version }}
        echo $CONCATENATED_VERSION
        echo tagged_image=$CONCATENATED_VERSION >> $GITHUB_OUTPUT
      shell: bash