name: promote_to_env
on:
  workflow_call:
    inputs:
      base-env:
        required: true
        type: string
        description: 'The base env that will be use to promote from'
        default: 'dev'
      promotion-env:
        description: 'The higher environment that the image will be promoted to.'
        required: true
        type: string
        default: 'staging'
    secrets:
      PR_TOKEN:
        required: true
        description: "Token that's scoped to the repo and has read, write, and PR create permissions"
      
jobs:
  promote_image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Source Code'
        id: checkout_source_code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Using GH token here because we're commiting to a non protected branch for the PR.
          ref: ${{ github.ref }}
      - name: Get base env image name
        id: get_lower_env_image
        run: |
          BASE_IMAGE=$(echo $(sed -n -e 's/.*image://p' kustomize/overlays/${{ inputs.base-env }}/deployment.yaml) | cut -c2- | rev | cut -c2- | rev)
          echo "tagged-image=$BASE_IMAGE" >> $GITHUB_OUTPUT
      - name: Update the image definition in the YAML
        id: find_and_replace_image
        uses: chippawah/composite-actions/find_and_replace_image@main
        with:
          tagged-image: ${{ steps.get_lower_env_image.outputs.tagged-image }}
          deployment-yaml-path: "kustomize/overlays/${{ inputs.promotion-env }}/deployment.yaml"
      - name: 'Open a PR'
        id: open_a_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PR_TOKEN }}
          branch: "promoting-${{ inputs.base-env }}-to-${{ inputs.promotion-env }}"
          body: "Automatic changes created by the `promote_to_environment` github action."
          commit-message: "Promotion of ${{ steps.get_lower_env_image.outputs.tagged-image }} from ${{ inputs.base-env }} to ${{ inputs.promotion-env }}"
      